import { expect } from "@playwright/test";
import { test } from "../fixtures";
// The link data is imported (not read from disk) because the `bunx --bun`
// runner bundles specs for a browser target and rejects `node:` builtins and
// JSON imports. The data module is emitted by `utils/generate-ci-links.ts`
// alongside `ci-links.json`. Note: the spec must not import the `Page` *type*
// from `@playwright/test` (even transitively) — that also breaks the `--bun`
// transform — so `scrollToBottom` takes an untyped `page`.
import { ciLinks } from "./ci-links.data";

/**
 * CI link-audit suite.
 *
 * Renders each internal link from `tests/ci-links.json` (generated by
 * `utils/generate-ci-links.ts`) in headless Chromium, asserting:
 *  - the HTTP response status is < 400
 *  - no browser console errors / page errors fired (captured by `fixtures.ts`)
 *
 * Each link is its own test, so the list reporter gives a terse pass/fail per
 * link (the link itself is the test name, so a failure shows both the error and
 * its source). On the homepage only we scroll incrementally to the bottom to
 * trigger lazy-loaded content.
 */

const links = ciLinks;

const HOMEPAGE = "/";

test.describe("ci-links", () => {
  for (const link of links) {
    test(`checks ${link}`, async ({ page }) => {
      const response = await page.goto(link, { waitUntil: "domcontentloaded" });
      // On the homepage only, scroll incrementally to the bottom with
      // `page.mouse.wheel` so lazy-loaded content (images, etc.) actually
      // mounts. We avoid `page.evaluate` and a standalone async helper here:
      // the `bunx --bun` runner bundles specs for a browser target that
      // mis-handles `evaluate` callbacks and `Promise`-annotated functions.
      if (link === HOMEPAGE) {
        for (let i = 0; i < 30; i++) {
          await page.mouse.wheel(0, 1000);
          await page.waitForTimeout(80);
        }
      }
      // Let hydration / late console errors surface before the fixtures assert.
      await page.waitForTimeout(300);
      expect(response?.status() ?? 0, `HTTP status for ${link}`).toBeLessThan(400);
    });
  }
});
