import { expect, type Page } from "@playwright/test";
import { test } from "../fixtures";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * CI link-audit suite.
 *
 * Reads `tests/ci-links.json` (generated by `utils/generate-ci-links.ts`) and
 * renders each internal link in headless Chromium, asserting:
 *  - the HTTP response status is < 400
 *  - no browser console errors / page errors fired (captured by `fixtures.ts`)
 *
 * Per-link `test.for` keeps this fast: tests run in parallel and the list
 * reporter gives a terse pass/fail per link (the link itself is the test name,
 * so a failure shows both the error and its source). On the homepage only we
 * scroll incrementally to the bottom to trigger lazy-loaded content.
 */

const data = JSON.parse(
  readFileSync(join(__dirname, "ci-links.json"), "utf-8"),
) as { links: string[] };
const links = data.links ?? [];

const HOMEPAGE = "/";

/** Incremental scroll to the bottom so lazy images/hydration run. */
async function scrollToBottom(page: Page): Promise<void> {
  await page.evaluate(
    () =>
      new Promise<void>((resolve) => {
        const step = Math.max(300, window.innerHeight * 0.8);
        let y = 0;
        const timer = setInterval(() => {
          window.scrollBy(0, step);
          y += step;
          if (y >= document.body.scrollHeight) {
            clearInterval(timer);
            resolve();
          }
        }, 80);
      }),
  );
}

test.describe("ci-links", () => {
  for (const link of links) {
    test(`checks ${link}`, async ({ page }) => {
      const response = await page.goto(link, { waitUntil: "domcontentloaded" });
      if (link === HOMEPAGE) {
        await scrollToBottom(page);
      }
      // Let hydration / late console errors surface before the fixtures assert.
      await page.waitForTimeout(300);
      expect(response?.status() ?? 0, `HTTP status for ${link}`).toBeLessThan(400);
    });
  }
});
